[package]
name = "bevy-getting-started"
version = "0.1.0"
edition = "2021"
description = "Bevy oyun motoru getting started ünitesi"

[dependencies]
bevy = "0.11.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
