[package]
name = "on-my-way"
version = "0.1.0"
edition = "2021"
description = "Saturn yolunda meteorlarla çarpışan bir uzay pilotunun hikayesi"
authors = ["BSŞ"]

[dependencies]
bevy = "0.11.0"
rand = "0.8.5"
