[package]
name = "dragon-fighter"
version = "0.1.0"
edition = "2021"
description = "A simple bevy game to learning game development"
authors = ["Burak Selim Şenyurt"]

[dependencies]
bevy = {version="0.8.1", features=["dynamic"]}
